// <auto-generated />
using System;
using Mentora.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mentora.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MentoraDbContext))]
    [Migration("20260430145540_AddLot2_Foundation")]
    partial class AddLot2_Foundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mentora.Core.Entities.AgentToken", b =>
                {
                    b.Property<Guid>("AgentTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AGENT_TOKEN_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AgentTokenCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AGENT_TOKEN_CREATED_DATE");

                    b.Property<DateTime>("AgentTokenExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AGENT_TOKEN_EXPIRATION_DATE");

                    b.Property<string>("AgentTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AGENT_TOKEN_HASH");

                    b.Property<bool>("AgentTokenIsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("AGENT_TOKEN_IS_REVOKED");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.HasKey("AgentTokenId");

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.ToTable("AGENT_TOKENS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.AuthOtp", b =>
                {
                    b.Property<Guid>("AuthOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AUTH_OTP_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthOtpCodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AUTH_OTP_CODE_HASH");

                    b.Property<DateTime>("AuthOtpCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_OTP_CREATED_DATE");

                    b.Property<DateTime>("AuthOtpExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_OTP_EXPIRATION_DATE");

                    b.Property<bool>("AuthOtpIsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("AUTH_OTP_IS_USED");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("AuthOtpId");

                    b.HasIndex("UserId");

                    b.ToTable("AUTH_OTPS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.AuthRefreshToken", b =>
                {
                    b.Property<Guid>("AuthRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AUTH_REFRESH_TOKEN_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AuthRefreshTokenCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_REFRESH_TOKEN_CREATED_DATE");

                    b.Property<DateTime>("AuthRefreshTokenExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_REFRESH_TOKEN_EXPIRATION_DATE");

                    b.Property<string>("AuthRefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AUTH_REFRESH_TOKEN_HASH");

                    b.Property<bool>("AuthRefreshTokenIsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("AUTH_REFRESH_TOKEN_IS_REVOKED");

                    b.Property<DateTime?>("AuthRefreshTokenRevokedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_REFRESH_TOKEN_REVOKED_DATE");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("AuthRefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("AUTH_REFRESH_TOKENS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.Coach", b =>
                {
                    b.Property<Guid>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CoachCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("COACH_CREATED_DATE");

                    b.Property<string>("CoachFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("COACH_FIRST_NAME");

                    b.Property<bool>("CoachIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("COACH_IS_ACTIVE");

                    b.Property<string>("CoachLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("COACH_LAST_NAME");

                    b.Property<string>("CoachPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("COACH_PHONE");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("CoachId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("COACHES", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.CoachParameter", b =>
                {
                    b.Property<Guid>("CoachParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_PARAMETER_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<int>("CoachParameterCancellationDelayHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24)
                        .HasColumnName("COACH_PARAMETER_CANCELLATION_DELAY_HOURS");

                    b.Property<DateTime>("CoachParameterCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("COACH_PARAMETER_CREATED_DATE");

                    b.Property<decimal>("CoachParameterHourlyRateEuros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(50.00m)
                        .HasColumnName("COACH_PARAMETER_HOURLY_RATE_EUROS");

                    b.Property<DateTime>("CoachParameterUpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("COACH_PARAMETER_UPDATED_DATE");

                    b.HasKey("CoachParameterId");

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.ToTable("COACH_PARAMETERS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.HealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("HealthChecks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Mentora API is live and connected to PostgreSQL!"
                        });
                });

            modelBuilder.Entity("Mentora.Core.Entities.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("MEMBER_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("MemberActivationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MEMBER_ACTIVATION_DATE");

                    b.Property<DateTime>("MemberCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MEMBER_CREATED_DATE");

                    b.Property<string>("MemberFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MEMBER_FIRST_NAME");

                    b.Property<bool>("MemberHasActivated")
                        .HasColumnType("boolean")
                        .HasColumnName("MEMBER_HAS_ACTIVATED");

                    b.Property<bool>("MemberIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("MEMBER_IS_ACTIVE");

                    b.Property<string>("MemberLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MEMBER_LAST_NAME");

                    b.Property<string>("MemberPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("MEMBER_PHONE");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("MemberId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MEMBERS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.MemberCoach", b =>
                {
                    b.Property<Guid>("MemberCoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("MEMBER_COACH_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_PRIMARY");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("MEMBER_ID");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("STARTED_AT")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MemberCoachId");

                    b.HasIndex("CoachId");

                    b.HasIndex("MemberId", "CoachId")
                        .IsUnique();

                    b.ToTable("MEMBER_COACHES", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.OfferProgram", b =>
                {
                    b.Property<Guid>("OfferProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("OFFER_PROGRAM_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<DateTime>("OfferProgramCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OFFER_PROGRAM_CREATED_DATE");

                    b.Property<bool>("OfferProgramIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("OFFER_PROGRAM_IS_ACTIVE");

                    b.Property<string>("OfferProgramName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("OFFER_PROGRAM_NAME");

                    b.HasKey("OfferProgramId");

                    b.HasIndex("CoachId", "OfferProgramName")
                        .IsUnique()
                        .HasDatabaseName("IX_OFFER_PROGRAMS_ACTIVE_NAME")
                        .HasFilter("\"OFFER_PROGRAM_IS_ACTIVE\" = true");

                    b.ToTable("OFFER_PROGRAMS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.SessionSlot", b =>
                {
                    b.Property<Guid>("SessionSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("SESSION_SLOT_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<DateTime>("SessionSlotCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_SLOT_CREATED_DATE");

                    b.Property<int>("SessionSlotDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("SESSION_SLOT_DURATION_MINUTES");

                    b.Property<DateTime>("SessionSlotEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_SLOT_END_DATE");

                    b.Property<bool>("SessionSlotIsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("SESSION_SLOT_IS_AVAILABLE");

                    b.Property<string>("SessionSlotOfferType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("SESSION_SLOT_OFFER_TYPE");

                    b.Property<DateTime>("SessionSlotStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_SLOT_START_DATE");

                    b.HasKey("SessionSlotId");

                    b.HasIndex("CoachId");

                    b.ToTable("SESSION_SLOTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_SESSION_SLOTS_END_AFTER_START", "\"SESSION_SLOT_END_DATE\" > \"SESSION_SLOT_START_DATE\"");
                        });
                });

            modelBuilder.Entity("Mentora.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("UserCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USER_CREATED_DATE");

                    b.Property<DateTime?>("UserDisabledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USER_DISABLED_DATE");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("USER_EMAIL");

                    b.Property<bool>("UserIsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("USER_IS_ENABLED");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("USER_LOGIN");

                    b.Property<DateTime?>("UserModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USER_MODIFICATION_DATE");

                    b.Property<string>("UserPsw")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("USER_PSW");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USER_ROLE");

                    b.HasKey("UserId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.AgentToken", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithOne("AgentToken")
                        .HasForeignKey("Mentora.Core.Entities.AgentToken", "CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Mentora.Core.Entities.AuthOtp", b =>
                {
                    b.HasOne("Mentora.Core.Entities.User", "User")
                        .WithMany("AuthOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Core.Entities.AuthRefreshToken", b =>
                {
                    b.HasOne("Mentora.Core.Entities.User", "User")
                        .WithMany("AuthRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Coach", b =>
                {
                    b.HasOne("Mentora.Core.Entities.User", "User")
                        .WithOne("Coach")
                        .HasForeignKey("Mentora.Core.Entities.Coach", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Core.Entities.CoachParameter", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithOne("CoachParameter")
                        .HasForeignKey("Mentora.Core.Entities.CoachParameter", "CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Member", b =>
                {
                    b.HasOne("Mentora.Core.Entities.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("Mentora.Core.Entities.Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Core.Entities.MemberCoach", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany("MemberCoaches")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.Member", "Member")
                        .WithMany("MemberCoaches")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Mentora.Core.Entities.OfferProgram", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany("OfferPrograms")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Mentora.Core.Entities.SessionSlot", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany("SessionSlots")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Coach", b =>
                {
                    b.Navigation("AgentToken");

                    b.Navigation("CoachParameter");

                    b.Navigation("MemberCoaches");

                    b.Navigation("OfferPrograms");

                    b.Navigation("SessionSlots");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Member", b =>
                {
                    b.Navigation("MemberCoaches");
                });

            modelBuilder.Entity("Mentora.Core.Entities.User", b =>
                {
                    b.Navigation("AuthOtps");

                    b.Navigation("AuthRefreshTokens");

                    b.Navigation("Coach");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
