// <auto-generated />
using System;
using System.Collections.Generic;
using Mentora.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mentora.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MentoraDbContext))]
    [Migration("20260619193709_AddConversationsAndMessages")]
    partial class AddConversationsAndMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mentora.Core.Entities.AgentToken", b =>
                {
                    b.Property<Guid>("AgentTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AGENT_TOKEN_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AgentTokenCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AGENT_TOKEN_CREATED_DATE");

                    b.Property<DateTime>("AgentTokenExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AGENT_TOKEN_EXPIRATION_DATE");

                    b.Property<string>("AgentTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AGENT_TOKEN_HASH");

                    b.Property<bool>("AgentTokenIsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("AGENT_TOKEN_IS_REVOKED");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.HasKey("AgentTokenId");

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.ToTable("AGENT_TOKENS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.AuthOtp", b =>
                {
                    b.Property<Guid>("AuthOtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AUTH_OTP_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthOtpCodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AUTH_OTP_CODE_HASH");

                    b.Property<DateTime>("AuthOtpCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_OTP_CREATED_DATE");

                    b.Property<DateTime>("AuthOtpExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_OTP_EXPIRATION_DATE");

                    b.Property<bool>("AuthOtpIsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("AUTH_OTP_IS_USED");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("AuthOtpId");

                    b.HasIndex("UserId");

                    b.ToTable("AUTH_OTPS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.AuthRefreshToken", b =>
                {
                    b.Property<Guid>("AuthRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AUTH_REFRESH_TOKEN_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AuthRefreshTokenCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_REFRESH_TOKEN_CREATED_DATE");

                    b.Property<DateTime>("AuthRefreshTokenExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_REFRESH_TOKEN_EXPIRATION_DATE");

                    b.Property<string>("AuthRefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AUTH_REFRESH_TOKEN_HASH");

                    b.Property<bool>("AuthRefreshTokenIsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("AUTH_REFRESH_TOKEN_IS_REVOKED");

                    b.Property<DateTime?>("AuthRefreshTokenRevokedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AUTH_REFRESH_TOKEN_REVOKED_DATE");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("AuthRefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("AUTH_REFRESH_TOKENS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CART_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("CART_COACH_ID");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CART_CREATED_DATE")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("CART_MEMBER_ID");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CART_UPDATED_DATE")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CartId");

                    b.HasIndex("CoachId");

                    b.HasIndex("MemberId", "CoachId")
                        .IsUnique()
                        .HasDatabaseName("IX_CARTS_MEMBER_COACH_UNIQUE");

                    b.ToTable("CARTS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CART_ITEM_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CART_ITEM_ADDED_DATE")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("CART_ITEM_CART_ID");

                    b.Property<Guid?>("PackId")
                        .HasColumnType("uuid")
                        .HasColumnName("CART_ITEM_PACK_ID");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("CART_ITEM_PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("CART_ITEM_QUANTITY");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("PackId");

                    b.HasIndex("ProductId");

                    b.ToTable("CART_ITEMS", null, t =>
                        {
                            t.HasCheckConstraint("CK_CART_ITEMS_PRODUCT_OR_PACK_XOR", "((\"CART_ITEM_PRODUCT_ID\" IS NOT NULL)::int + (\"CART_ITEM_PACK_ID\" IS NOT NULL)::int) = 1");
                        });
                });

            modelBuilder.Entity("Mentora.Core.Entities.Coach", b =>
                {
                    b.Property<Guid>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CoachCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("COACH_CREATED_DATE");

                    b.Property<string>("CoachFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("COACH_FIRST_NAME");

                    b.Property<bool>("CoachIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("COACH_IS_ACTIVE");

                    b.Property<string>("CoachLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("COACH_LAST_NAME");

                    b.Property<string>("CoachPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("COACH_PHONE");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("CoachId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("COACHES", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.CoachParameter", b =>
                {
                    b.Property<Guid>("CoachParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_PARAMETER_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<int>("CoachParameterCancellationDelayHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24)
                        .HasColumnName("COACH_PARAMETER_CANCELLATION_DELAY_HOURS");

                    b.Property<DateTime>("CoachParameterCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("COACH_PARAMETER_CREATED_DATE");

                    b.Property<decimal>("CoachParameterHourlyRateEuros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(50.00m)
                        .HasColumnName("COACH_PARAMETER_HOURLY_RATE_EUROS");

                    b.Property<DateTime>("CoachParameterUpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("COACH_PARAMETER_UPDATED_DATE");

                    b.HasKey("CoachParameterId");

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.ToTable("COACH_PARAMETERS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.Conversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CONVERSATION_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<DateTime>("ConversationCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CONVERSATION_CREATED_DATE")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("ConversationLastMessageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CONVERSATION_LAST_MESSAGE_DATE");

                    b.Property<string>("ConversationVisioUrl")
                        .HasColumnType("text")
                        .HasColumnName("CONVERSATION_VISIO_URL");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("MEMBER_ID");

                    b.HasKey("ConversationId");

                    b.HasIndex("CoachId");

                    b.HasIndex("MemberId", "CoachId")
                        .IsUnique()
                        .HasDatabaseName("IX_CONVERSATIONS_MEMBER_COACH");

                    b.ToTable("CONVERSATIONS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.HealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("HealthChecks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Mentora API is live and connected to PostgreSQL!"
                        });
                });

            modelBuilder.Entity("Mentora.Core.Entities.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("MEMBER_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("MemberActivationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MEMBER_ACTIVATION_DATE");

                    b.Property<DateTime>("MemberCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MEMBER_CREATED_DATE");

                    b.Property<string>("MemberFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MEMBER_FIRST_NAME");

                    b.Property<bool>("MemberHasActivated")
                        .HasColumnType("boolean")
                        .HasColumnName("MEMBER_HAS_ACTIVATED");

                    b.Property<bool>("MemberIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("MEMBER_IS_ACTIVE");

                    b.Property<string>("MemberLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MEMBER_LAST_NAME");

                    b.Property<string>("MemberPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("MEMBER_PHONE");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("MemberId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MEMBERS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.MemberCoach", b =>
                {
                    b.Property<Guid>("MemberCoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("MEMBER_COACH_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_PRIMARY");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("MEMBER_ID");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("STARTED_AT")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MemberCoachId");

                    b.HasIndex("CoachId");

                    b.HasIndex("MemberId", "CoachId")
                        .IsUnique();

                    b.ToTable("MEMBER_COACHES", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("MESSAGE_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONVERSATION_ID");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MESSAGE_CONTENT");

                    b.Property<bool>("MessageIsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("MESSAGE_IS_READ");

                    b.Property<DateTime?>("MessageReadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MESSAGE_READ_DATE");

                    b.Property<Guid>("MessageSenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("MESSAGE_SENDER_ID");

                    b.Property<string>("MessageSenderType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("MESSAGE_SENDER_TYPE");

                    b.Property<DateTime>("MessageSentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("MESSAGE_SENT_DATE")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId", "MessageSentDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_MESSAGES_CONVERSATION_SENT_DESC");

                    b.ToTable("MESSAGES", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.OfferProgram", b =>
                {
                    b.Property<Guid>("OfferProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("OFFER_PROGRAM_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<DateTime>("OfferProgramCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OFFER_PROGRAM_CREATED_DATE");

                    b.Property<bool>("OfferProgramIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("OFFER_PROGRAM_IS_ACTIVE");

                    b.Property<string>("OfferProgramName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("OFFER_PROGRAM_NAME");

                    b.HasKey("OfferProgramId");

                    b.HasIndex("CoachId", "OfferProgramName")
                        .IsUnique()
                        .HasDatabaseName("IX_OFFER_PROGRAMS_ACTIVE_NAME")
                        .HasFilter("\"OFFER_PROGRAM_IS_ACTIVE\" = true");

                    b.ToTable("OFFER_PROGRAMS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ORDER_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("ORDER_COACH_ID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ORDER_CREATED_DATE");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("ORDER_MEMBER_ID");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ORDER_PAID_AT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ORDER_STATUS")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<string>("StripeCheckoutUrl")
                        .HasColumnType("text")
                        .HasColumnName("ORDER_STRIPE_CHECKOUT_URL");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ORDER_STRIPE_SESSION_ID");

                    b.Property<decimal>("TotalEuros")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ORDER_TOTAL_EUROS");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ORDER_UPDATED_DATE");

                    b.HasKey("OrderId");

                    b.HasIndex("CoachId");

                    b.HasIndex("MemberId");

                    b.HasIndex("StripeSessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ORDERS_STRIPE_SESSION_ID_UNIQUE")
                        .HasFilter("\"ORDER_STRIPE_SESSION_ID\" IS NOT NULL");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ORDER_ITEM_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("ORDER_ITEM_DURATION_MINUTES");

                    b.Property<decimal>("LineTotalEuros")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ORDER_ITEM_LINE_TOTAL_EUROS");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ORDER_ITEM_OFFER_TYPE");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("ORDER_ITEM_ORDER_ID");

                    b.Property<decimal>("OrderItemOriginalUnitPriceEuros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ORDER_ITEM_ORIGINAL_UNIT_PRICE_EUROS");

                    b.Property<decimal?>("OrderItemPackDiscountPercentApplied")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ORDER_ITEM_PACK_DISCOUNT_PERCENT_APPLIED");

                    b.Property<Guid?>("PackId")
                        .HasColumnType("uuid")
                        .HasColumnName("ORDER_ITEM_PACK_ID");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("ORDER_ITEM_PRODUCT_ID");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ORDER_ITEM_PRODUCT_NAME");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("ORDER_ITEM_QUANTITY");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ORDER_ITEM_SPORT")
                        .HasDefaultValueSql("'TRAINING'");

                    b.Property<decimal>("UnitPriceEuros")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ORDER_ITEM_UNIT_PRICE_EUROS");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("ORDER_ITEMS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUCT_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<Guid>("OfferProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("OFFER_PROGRAM_ID");

                    b.Property<DateTime>("ProductCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PRODUCT_CREATED_DATE");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text")
                        .HasColumnName("PRODUCT_DESCRIPTION");

                    b.Property<int>("ProductDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("PRODUCT_DURATION_MINUTES");

                    b.Property<string>("ProductLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PRODUCT_LOCATION");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("PRODUCT_NAME");

                    b.Property<string>("ProductOfferNature")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasDefaultValue("CLASSIQUE")
                        .HasColumnName("PRODUCT_OFFER_NATURE");

                    b.Property<string>("ProductOfferType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PRODUCT_OFFER_TYPE");

                    b.Property<decimal>("ProductPriceEuros")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("PRODUCT_PRICE_EUROS");

                    b.Property<string>("ProductSport")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PRODUCT_SPORT")
                        .HasDefaultValueSql("'TRAINING'");

                    b.Property<string>("ProductStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PRODUCT_STATUS")
                        .HasDefaultValueSql("'DRAFT'");

                    b.Property<List<string>>("ProductTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("PRODUCT_TAGS");

                    b.Property<DateTime>("ProductUpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PRODUCT_UPDATED_DATE");

                    b.HasKey("ProductId");

                    b.HasIndex("OfferProgramId");

                    b.HasIndex("CoachId", "ProductStatus")
                        .HasDatabaseName("IX_PRODUCTS_COACH_STATUS");

                    b.ToTable("PRODUCTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_PRODUCTS_DURATION_POSITIVE", "\"PRODUCT_DURATION_MINUTES\" > 0");

                            t.HasCheckConstraint("CK_PRODUCTS_PRICE_NON_NEGATIVE", "\"PRODUCT_PRICE_EUROS\" >= 0");
                        });
                });

            modelBuilder.Entity("Mentora.Core.Entities.ProductPack", b =>
                {
                    b.Property<Guid>("ProductPackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUCT_PACK_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<DateTime>("ProductPackCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PRODUCT_PACK_CREATED_DATE");

                    b.Property<string>("ProductPackDescription")
                        .HasColumnType("text")
                        .HasColumnName("PRODUCT_PACK_DESCRIPTION");

                    b.Property<decimal>("ProductPackDiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("PRODUCT_PACK_DISCOUNT_PERCENT");

                    b.Property<string>("ProductPackName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("PRODUCT_PACK_NAME");

                    b.Property<decimal>("ProductPackPriceEuros")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("PRODUCT_PACK_PRICE_EUROS");

                    b.Property<string>("ProductPackStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PRODUCT_PACK_STATUS")
                        .HasDefaultValueSql("'DRAFT'");

                    b.Property<DateTime>("ProductPackUpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PRODUCT_PACK_UPDATED_DATE");

                    b.HasKey("ProductPackId");

                    b.HasIndex("CoachId", "ProductPackStatus")
                        .HasDatabaseName("IX_PRODUCT_PACKS_COACH_STATUS");

                    b.ToTable("PRODUCT_PACKS", null, t =>
                        {
                            t.HasCheckConstraint("CK_PRODUCT_PACKS_DISCOUNT_PERCENT_RANGE", "\"PRODUCT_PACK_DISCOUNT_PERCENT\" >= 0 AND \"PRODUCT_PACK_DISCOUNT_PERCENT\" <= 100");

                            t.HasCheckConstraint("CK_PRODUCT_PACKS_PRICE_NON_NEGATIVE", "\"PRODUCT_PACK_PRICE_EUROS\" >= 0");
                        });
                });

            modelBuilder.Entity("Mentora.Core.Entities.ProductPackItem", b =>
                {
                    b.Property<Guid>("ProductPackItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUCT_PACK_ITEM_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<Guid>("ProductPackId")
                        .HasColumnType("uuid")
                        .HasColumnName("PRODUCT_PACK_ID");

                    b.Property<int>("ProductPackItemQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("PRODUCT_PACK_ITEM_QUANTITY");

                    b.HasKey("ProductPackItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductPackId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_PRODUCT_PACK_ITEMS_PACK_PRODUCT_UNIQUE");

                    b.ToTable("PRODUCT_PACK_ITEMS", null, t =>
                        {
                            t.HasCheckConstraint("CK_PRODUCT_PACK_ITEMS_QUANTITY_MIN_1", "\"PRODUCT_PACK_ITEM_QUANTITY\" >= 1");
                        });
                });

            modelBuilder.Entity("Mentora.Core.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("SESSION_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("SessionCancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("SESSION_CANCELLATION_REASON");

                    b.Property<DateTime?>("SessionCancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_CANCELLED_AT");

                    b.Property<string>("SessionCancelledBy")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("SESSION_CANCELLED_BY");

                    b.Property<Guid>("SessionCoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("SESSION_COACH_ID");

                    b.Property<DateTime?>("SessionCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_COMPLETED_AT");

                    b.Property<DateTime>("SessionCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_CREATED_DATE");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("SESSION_DURATION_MINUTES");

                    b.Property<Guid>("SessionMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("SESSION_MEMBER_ID");

                    b.Property<string>("SessionOfferType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("SESSION_OFFER_TYPE");

                    b.Property<Guid>("SessionProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("SESSION_PRODUCT_ID");

                    b.Property<DateTime>("SessionScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_SCHEDULED_AT");

                    b.Property<Guid>("SessionSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("SESSION_SLOT_ID");

                    b.Property<string>("SessionSport")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("SESSION_SPORT");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("SESSION_STATUS")
                        .HasDefaultValueSql("'SCHEDULED'");

                    b.Property<DateTime>("SessionUpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_UPDATED_DATE");

                    b.Property<string>("SessionVisioUrl")
                        .HasColumnType("text")
                        .HasColumnName("SESSION_VISIO_URL");

                    b.Property<Guid>("SessionVoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("SESSION_VOUCHER_ID");

                    b.HasKey("SessionId");

                    b.HasIndex("SessionSlotId");

                    b.HasIndex("SessionVoucherId");

                    b.HasIndex("SessionCoachId", "SessionScheduledAt")
                        .HasDatabaseName("IX_SESSIONS_COACH_SCHEDULED_AT");

                    b.HasIndex("SessionMemberId", "SessionStatus")
                        .HasDatabaseName("IX_SESSIONS_MEMBER_STATUS");

                    b.ToTable("SESSIONS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.SessionSlot", b =>
                {
                    b.Property<Guid>("SessionSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("SESSION_SLOT_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("COACH_ID");

                    b.Property<DateTime>("SessionSlotCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_SLOT_CREATED_DATE");

                    b.Property<int>("SessionSlotDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("SESSION_SLOT_DURATION_MINUTES");

                    b.Property<DateTime>("SessionSlotEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_SLOT_END_DATE");

                    b.Property<bool>("SessionSlotIsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("SESSION_SLOT_IS_AVAILABLE");

                    b.Property<string>("SessionSlotOfferType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("SESSION_SLOT_OFFER_TYPE");

                    b.Property<DateTime>("SessionSlotStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SESSION_SLOT_START_DATE");

                    b.HasKey("SessionSlotId");

                    b.HasIndex("CoachId");

                    b.ToTable("SESSION_SLOTS", null, t =>
                        {
                            t.HasCheckConstraint("CK_SESSION_SLOTS_END_AFTER_START", "\"SESSION_SLOT_END_DATE\" > \"SESSION_SLOT_START_DATE\"");
                        });
                });

            modelBuilder.Entity("Mentora.Core.Entities.SessionVoucher", b =>
                {
                    b.Property<Guid>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("VOUCHER_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("VOUCHER_COACH_ID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VOUCHER_CREATED_DATE");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("VOUCHER_DURATION_MINUTES");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("VOUCHER_MEMBER_ID");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("VOUCHER_OFFER_TYPE");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("VOUCHER_ORDER_ITEM_ID");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("VOUCHER_PRODUCT_ID");

                    b.Property<Guid?>("ReservedSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("VOUCHER_RESERVED_SESSION_ID");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("VOUCHER_SPORT")
                        .HasDefaultValueSql("'TRAINING'");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("VOUCHER_STATUS")
                        .HasDefaultValueSql("'AVAILABLE'");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VOUCHER_UPDATED_DATE");

                    b.HasKey("VoucherId");

                    b.HasIndex("CoachId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ReservedSessionId");

                    b.HasIndex("MemberId", "Status")
                        .HasDatabaseName("IX_SESSION_VOUCHERS_MEMBER_STATUS");

                    b.ToTable("SESSION_VOUCHERS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.StripeWebhookEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("EVENT_ID");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EVENT_TYPE");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("EVENT_PAYLOAD");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EVENT_PROCESSED_AT");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text")
                        .HasColumnName("EVENT_PROCESSING_ERROR");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EVENT_RECEIVED_AT")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("EVENT_STATUS")
                        .HasDefaultValueSql("'RECEIVED'");

                    b.HasKey("EventId");

                    b.ToTable("STRIPE_WEBHOOK_EVENTS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("UserCreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USER_CREATED_DATE");

                    b.Property<DateTime?>("UserDisabledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USER_DISABLED_DATE");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("USER_EMAIL");

                    b.Property<bool>("UserIsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("USER_IS_ENABLED");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("USER_LOGIN");

                    b.Property<DateTime?>("UserModificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USER_MODIFICATION_DATE");

                    b.Property<string>("UserPsw")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("USER_PSW");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USER_ROLE");

                    b.HasKey("UserId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Mentora.Core.Entities.AgentToken", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithOne("AgentToken")
                        .HasForeignKey("Mentora.Core.Entities.AgentToken", "CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Mentora.Core.Entities.AuthOtp", b =>
                {
                    b.HasOne("Mentora.Core.Entities.User", "User")
                        .WithMany("AuthOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Core.Entities.AuthRefreshToken", b =>
                {
                    b.HasOne("Mentora.Core.Entities.User", "User")
                        .WithMany("AuthRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Cart", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Mentora.Core.Entities.CartItem", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.ProductPack", "Pack")
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mentora.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cart");

                    b.Navigation("Pack");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Coach", b =>
                {
                    b.HasOne("Mentora.Core.Entities.User", "User")
                        .WithOne("Coach")
                        .HasForeignKey("Mentora.Core.Entities.Coach", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Core.Entities.CoachParameter", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithOne("CoachParameter")
                        .HasForeignKey("Mentora.Core.Entities.CoachParameter", "CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Conversation", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Member", b =>
                {
                    b.HasOne("Mentora.Core.Entities.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("Mentora.Core.Entities.Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mentora.Core.Entities.MemberCoach", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany("MemberCoaches")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.Member", "Member")
                        .WithMany("MemberCoaches")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Message", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Mentora.Core.Entities.OfferProgram", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany("OfferPrograms")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Order", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Mentora.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Product", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany("Products")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.OfferProgram", "OfferProgram")
                        .WithMany("Products")
                        .HasForeignKey("OfferProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("OfferProgram");
                });

            modelBuilder.Entity("Mentora.Core.Entities.ProductPack", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany("ProductPacks")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Mentora.Core.Entities.ProductPackItem", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Product", "Product")
                        .WithMany("PackItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.ProductPack", "ProductPack")
                        .WithMany("Items")
                        .HasForeignKey("ProductPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductPack");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Session", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("SessionCoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("SessionMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.SessionSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SessionSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.SessionVoucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("SessionVoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Member");

                    b.Navigation("Slot");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Mentora.Core.Entities.SessionSlot", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany("SessionSlots")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Mentora.Core.Entities.SessionVoucher", b =>
                {
                    b.HasOne("Mentora.Core.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mentora.Core.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("ReservedSessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SESSION_VOUCHERS_RESERVED_SESSION");

                    b.Navigation("Coach");

                    b.Navigation("Member");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Coach", b =>
                {
                    b.Navigation("AgentToken");

                    b.Navigation("CoachParameter");

                    b.Navigation("MemberCoaches");

                    b.Navigation("OfferPrograms");

                    b.Navigation("ProductPacks");

                    b.Navigation("Products");

                    b.Navigation("SessionSlots");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Member", b =>
                {
                    b.Navigation("MemberCoaches");
                });

            modelBuilder.Entity("Mentora.Core.Entities.OfferProgram", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Mentora.Core.Entities.Product", b =>
                {
                    b.Navigation("PackItems");
                });

            modelBuilder.Entity("Mentora.Core.Entities.ProductPack", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Mentora.Core.Entities.User", b =>
                {
                    b.Navigation("AuthOtps");

                    b.Navigation("AuthRefreshTokens");

                    b.Navigation("Coach");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
