using Mentora.Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Mentora.API.Controllers.Member;

/// <summary>Provides read-only access to the authenticated member's orders.</summary>
[ApiController]
[Route("api/v1/member/orders")]
[Authorize(Policy = "MemberOnly")]
[ApiExplorerSettings(GroupName = "mobile")]
[Tags("Member — Orders")]
public class MemberOrdersController(IMemberOrderService memberOrderService) : ControllerBase
{
    /// <summary>
    /// Returns a paginated list of the authenticated member's orders, newest first.
    /// </summary>
    /// <remarks>
    /// Orders are sorted by creation date descending, then by order ID descending as a stable tiebreaker.
    ///
    /// Accepted values for <paramref name="status"/>: <c>PENDING</c>, <c>PAID</c>, <c>EXPIRED</c>, <c>FAILED</c>.
    /// Any other value (including lowercase or integers) returns 400.
    /// When <paramref name="status"/> is absent, all statuses are returned.
    ///
    /// Pagination is cursor-based. When <c>nextCursor</c> is non-null in the response, pass it as
    /// the <paramref name="cursor"/> query parameter on the next request to retrieve the following page.
    /// </remarks>
    /// <param name="status">
    /// Optional status filter. Accepted: <c>PENDING</c> | <c>PAID</c> | <c>EXPIRED</c> | <c>FAILED</c>.
    /// </param>
    /// <param name="limit">Page size. Default: 20. Accepted range: [1..100].</param>
    /// <param name="cursor">Opaque pagination cursor returned by the previous page response.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A paginated list of orders with an optional cursor for the next page.</returns>
    [HttpGet]
    [ProducesResponseType(typeof(object), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> GetAll(
        [FromQuery] string? status = null,
        [FromQuery] int     limit  = 20,
        [FromQuery] string? cursor = null,
        CancellationToken ct = default)
    {
        var memberId = Guid.Parse(User.FindFirst("memberId")!.Value);
        var result   = await memberOrderService.ListAsync(memberId, status, limit, cursor, ct);
        return Ok(new { success = true, data = result, error = (string?)null, statusCode = 200 });
    }

    /// <summary>
    /// Returns the full detail of a single order, including line items and session vouchers.
    /// </summary>
    /// <remarks>
    /// Returns 404 whether the order does not exist OR exists but belongs to a different member.
    /// The two cases are intentionally indistinguishable to prevent information leakage.
    ///
    /// The <c>vouchers</c> array is empty while the order is in <c>PENDING</c> status.
    /// Vouchers are generated by the Stripe webhook once the payment is confirmed (<c>PAID</c>).
    /// Poll this endpoint after the Stripe redirect to pick up the freshly created vouchers.
    /// </remarks>
    /// <param name="orderId">Unique identifier of the order.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The full order detail including items and vouchers.</returns>
    [HttpGet("{orderId:guid}")]
    [ProducesResponseType(typeof(object), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetById(Guid orderId, CancellationToken ct)
    {
        var memberId = Guid.Parse(User.FindFirst("memberId")!.Value);
        var result   = await memberOrderService.GetDetailAsync(memberId, orderId, ct);
        return Ok(new { success = true, data = result, error = (string?)null, statusCode = 200 });
    }
}
